spring:
  ai:
    openai:
      base-url: ${spring.ai.openai.base-url}
      api-key: ${spring.ai.openai.api-key}
      chat:
        options:
          model: qwen-max-latest
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
    vectorstore:
      redis:
        initialize-schema: true
        index: 0
        prefix: "doc:" # 向量库key前缀


  rabbitmq:
    host: 121.40.147.57
    port: 5672
    virtual-host: /
    username: lgh
    password: 123456
    listener:
      simple:
        prefetch: 1



langchain4j:
  open-ai:
    streaming-chat-model: #流式模型配置
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-ea422ccad9354bc0afb3784e46154364
      model-name: qwen-plus
      log-requests: true #请求消息日志
      log-responses: true #响应消息日志