server:
  port: 8080
spring:
  profiles:
    active: dev
    include: file,extend  # 引入"file"环境的配置（即application-file.yml）
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${spring.datasource.druid.driver-class-name}
      url: ${spring.datasource.druid.url}
      username: ${spring.datasource.druid.username}
      password: ${spring.datasource.druid.password}
  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}
      database: ${spring.data.redis.database}
      password: ${spring.data.redis.password}

# knife4j配置
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: default
      paths-to-match: /**
      packages-to-scan: com.zl
knife4j:
  enable: true



# Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lgh.model.entity
  configuration:
    map-underscore-to-camel-case: true




zl:
  framework:
    #Security框架配置
    security:
      ignore-url:
        - /resource/menus/**
        - /resource/myButten/**
        - /customer/**
        - /web/login
        - /web/logout
        - /web/**
        - /ws/**
        - /doc.html/**
        - /*-swagger/**
        - /swagger-resources/**
        - /v3/api-docs/**
        - /webjars/**
        - /common/**
        - /swagger-ui/**
      defaule-password: 123456

  # token配置
  token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 1800000

  #阿里云平台配置
  aliyun:
    access-key-id: ${zl.aliyun.access-key-id}
    access-key-secret: ${zl.aliyun.access-key-secret}





#日志记录 - 详细配置请参考 logback-spring.xml
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com:
      zl: DEBUG